name: .NET + Docker CI

on:
  push:
    branches: ["$default-branch"]
  pull_request:
    branches: ["$default-branch"]

permissions:
  contents: read
  packages: write
  security-events: write
  pull-requests: read

jobs:
  pipeline:
    uses: rios0rios0/pipelines/.github/workflows/dotnet-docker.yaml@v3
    secrets: inherit
